
spring.datasource.url=jdbc:postgresql://dpg-d7j3juhj2pic73b7e4v0-a.singapore-postgres.render.com/moneymanager_wngo
spring.datasource.username=moneymanager_wngo_user
spring.datasource.password=VeIKd1XtJvGcDol1Zf7XTGVhyvnBK1T3
